"$schema" = "https://starship.rs/config-schema.json"

format = """
[](surface0)\
$os\
$username\
[](bg:teal fg:surface0)\
$directory\
[](fg:teal bg:green)\
$git_branch\
$git_status\
[](fg:green bg:sky)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:sky bg:lavender)\
$docker_context\
[](fg:lavender bg:lavender)\
$time\
[ ](fg:lavender)\
$line_break$character
"""

palette = "catppuccin_mocha"

# ========================
# Palette
# ========================

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# ========================
# OS
# ========================

[os]
disabled = false
style = "bg:surface0 fg:text"
format = "[ $symbol ]($style)"

[os.symbols]
CachyOS = ""
Arch = ""
Linux = "󰌽"
Ubuntu = "󰕈"
Fedora = "󰣛"
Debian = "󰣚"
Macos = ""
Windows = "󰍲"

# ========================
# Username
# ========================

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = "[ $user ]($style)"

# ========================
# Directory
# ========================

[directory]
style = "fg:mantle bg:teal"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# ========================
# Git
# ========================

[git_branch]
symbol = ""
style = "bg:green"
format = "[[ $symbol $branch ](fg:base bg:green)]($style)"

[git_status]
style = "bg:green"
format = "[[($all_status$ahead_behind )](fg:base bg:green)]($style)"

# ========================
# Languages
# ========================

[nodejs]
symbol = ""
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[c]
symbol = " "
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[rust]
symbol = ""
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[golang]
symbol = ""
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[php]
symbol = ""
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[java]
symbol = " "
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[kotlin]
symbol = ""
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[haskell]
symbol = ""
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

[python]
symbol = ""
style = "bg:sky"
format = "[[ $symbol( $version) ](fg:mantle bg:sky)]($style)"

# ========================
# Docker
# ========================

[docker_context]
symbol = ""
style = "bg:lavender"
format = "[[ $symbol( $context) ](fg:mantle bg:lavender)]($style)"

# ========================
# Time
# ========================

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = "[[  $time ](fg:mantle bg:lavender)]($style)"

# ========================
# Line Break
# ========================

[line_break]
disabled = false

# ========================
# Character
# ========================

[character]
disabled = false
success_symbol = "[❯](bold fg:sky)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:green)"
vimcmd_replace_one_symbol = "[❮](bold fg:sky)"
vimcmd_replace_symbol = "[❮](bold fg:sky)"
vimcmd_visual_symbol = "[❮](bold fg:lavender)"