general {
    grace = 0
    disable_loading_bar = false
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 0.9
    brightness = 0.8
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(E5E7EBFF)
    font_size = 80
    font_family = JetBrains Mono Nerd Font
    position = 0,300
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgba(A78BFAFF)
    font_size = 22
    font_family = JetBrains Mono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}
input-field {
   size = 300, 55
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = rgba(A78BFAFF)
    inner_color = rgba(111827CC)
    font_color = rgba(E5E7EBFF)
    fade_on_empty = false
    placeholder_text = <span foreground="##A78BFA">Enter Password...</span>
    position = 0, -400
    halign = center
    valign = center
}
animations{
enabled = true
}
