general {
    grace = 0
    disable_loading_bar = false
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 0.9
    brightness = 0.8
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(E5E7EBFF)
    font_size = 80
    font_family = JetBrains Mono Nerd Font
    position = 0, 150
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(151515)
    inner_color = rgb(202020)
    font_color = rgb(ffffff)
    fade_on_empty = false
    rounding = 10
    position = 0, -20
    halign = center
    valign = center
}

animations{
enabled = true
}
